language: go
go:
- '1.15.x'

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: "Testing stage"
      name: "Test datastore dshelp suite"
      script:
        - go test -v -run "TestDatastoreSuite" .
    - name: "Test CRDT datastore"
      script:
        - go test -v -run "TestCRDT" -race -covermode=atomic -coverprofile=coverage.txt .
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: "staticcheck"
      script:
        - go get honnef.co/go/tools/cmd/staticcheck
        - staticcheck
