// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bcast.proto

package crdt_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CRDTBroadcast struct {
	Heads                []*Head  `protobuf:"bytes,1,rep,name=Heads,proto3" json:"Heads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CRDTBroadcast) Reset()         { *m = CRDTBroadcast{} }
func (m *CRDTBroadcast) String() string { return proto.CompactTextString(m) }
func (*CRDTBroadcast) ProtoMessage()    {}
func (*CRDTBroadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_05914c14e19179d7, []int{0}
}

func (m *CRDTBroadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CRDTBroadcast.Unmarshal(m, b)
}
func (m *CRDTBroadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CRDTBroadcast.Marshal(b, m, deterministic)
}
func (m *CRDTBroadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CRDTBroadcast.Merge(m, src)
}
func (m *CRDTBroadcast) XXX_Size() int {
	return xxx_messageInfo_CRDTBroadcast.Size(m)
}
func (m *CRDTBroadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_CRDTBroadcast.DiscardUnknown(m)
}

var xxx_messageInfo_CRDTBroadcast proto.InternalMessageInfo

func (m *CRDTBroadcast) GetHeads() []*Head {
	if m != nil {
		return m.Heads
	}
	return nil
}

type Head struct {
	Cid                  []byte   `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_05914c14e19179d7, []int{1}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func init() {
	proto.RegisterType((*CRDTBroadcast)(nil), "crdt.pb.CRDTBroadcast")
	proto.RegisterType((*Head)(nil), "crdt.pb.Head")
}

func init() { proto.RegisterFile("bcast.proto", fileDescriptor_05914c14e19179d7) }

var fileDescriptor_05914c14e19179d7 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4a, 0x4e, 0x2c,
	0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2e, 0x4a, 0x29, 0xd1, 0x2b, 0x48,
	0x52, 0x32, 0xe1, 0xe2, 0x75, 0x0e, 0x72, 0x09, 0x71, 0x2a, 0xca, 0x4f, 0x4c, 0x01, 0xc9, 0x0b,
	0x29, 0x73, 0xb1, 0x7a, 0xa4, 0x26, 0xa6, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xf1,
	0xea, 0x41, 0x55, 0xea, 0x81, 0x44, 0x83, 0x20, 0x72, 0x4a, 0x12, 0x5c, 0x2c, 0x20, 0x86, 0x90,
	0x00, 0x17, 0xb3, 0x73, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x88, 0x99, 0xc4,
	0x06, 0x36, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x43, 0xaa, 0x19, 0xaf, 0x6e, 0x00, 0x00,
	0x00,
}
