// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: bcast.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateBroadcast struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Members       map[string]*Participant `protobuf:"bytes,1,rep,name=Members,proto3" json:"Members,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Map of participants
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateBroadcast) Reset() {
	*x = StateBroadcast{}
	mi := &file_bcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateBroadcast) ProtoMessage() {}

func (x *StateBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_bcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateBroadcast.ProtoReflect.Descriptor instead.
func (*StateBroadcast) Descriptor() ([]byte, []int) {
	return file_bcast_proto_rawDescGZIP(), []int{0}
}

func (x *StateBroadcast) GetMembers() map[string]*Participant {
	if x != nil {
		return x.Members
	}
	return nil
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BestBefore    uint64                 `protobuf:"varint,1,opt,name=BestBefore,proto3" json:"BestBefore,omitempty"`                                                                      // Timestamp for garbage collection
	DagHeads      []*Head                `protobuf:"bytes,2,rep,name=DagHeads,proto3" json:"DagHeads,omitempty"`                                                                           // List of DAG heads
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // A map to hold arbitrary metadata about the participant
	Snapshot      *Snapshot              `protobuf:"bytes,4,opt,name=Snapshot,proto3" json:"Snapshot,omitempty"`                                                                           // latest HAMT snapshot head
	StateSeq      uint32                 `protobuf:"varint,5,opt,name=StateSeq,proto3" json:"StateSeq,omitempty"`                                                                          // State sequence number for ordering updates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_bcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_bcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_bcast_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetBestBefore() uint64 {
	if x != nil {
		return x.BestBefore
	}
	return 0
}

func (x *Participant) GetDagHeads() []*Head {
	if x != nil {
		return x.DagHeads
	}
	return nil
}

func (x *Participant) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Participant) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *Participant) GetStateSeq() uint32 {
	if x != nil {
		return x.StateSeq
	}
	return 0
}

type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"` // CID representing a head
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_bcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_bcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_bcast_proto_rawDescGZIP(), []int{2}
}

func (x *Head) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotKey   *Head                  `protobuf:"bytes,1,opt,name=SnapshotKey,proto3" json:"SnapshotKey,omitempty"` // HAMT wrapper root
	DagHead       *Head                  `protobuf:"bytes,2,opt,name=DagHead,proto3" json:"DagHead,omitempty"`         // DAG node that was compacted
	Height        uint64                 `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"`          // DAG height at compaction
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_bcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_bcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_bcast_proto_rawDescGZIP(), []int{3}
}

func (x *Snapshot) GetSnapshotKey() *Head {
	if x != nil {
		return x.SnapshotKey
	}
	return nil
}

func (x *Snapshot) GetDagHead() *Head {
	if x != nil {
		return x.DagHead
	}
	return nil
}

func (x *Snapshot) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_bcast_proto protoreflect.FileDescriptor

const file_bcast_proto_rawDesc = "" +
	"\n" +
	"\vbcast.proto\x12\acrdt.pb\"\xa2\x01\n" +
	"\x0eStateBroadcast\x12>\n" +
	"\aMembers\x18\x01 \x03(\v2$.crdt.pb.StateBroadcast.MembersEntryR\aMembers\x1aP\n" +
	"\fMembersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.crdt.pb.ParticipantR\x05value:\x028\x01\"\xa0\x02\n" +
	"\vParticipant\x12\x1e\n" +
	"\n" +
	"BestBefore\x18\x01 \x01(\x04R\n" +
	"BestBefore\x12)\n" +
	"\bDagHeads\x18\x02 \x03(\v2\r.crdt.pb.HeadR\bDagHeads\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".crdt.pb.Participant.MetadataEntryR\bmetadata\x12-\n" +
	"\bSnapshot\x18\x04 \x01(\v2\x11.crdt.pb.SnapshotR\bSnapshot\x12\x1a\n" +
	"\bStateSeq\x18\x05 \x01(\rR\bStateSeq\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x18\n" +
	"\x04Head\x12\x10\n" +
	"\x03Cid\x18\x01 \x01(\fR\x03Cid\"|\n" +
	"\bSnapshot\x12/\n" +
	"\vSnapshotKey\x18\x01 \x01(\v2\r.crdt.pb.HeadR\vSnapshotKey\x12'\n" +
	"\aDagHead\x18\x02 \x01(\v2\r.crdt.pb.HeadR\aDagHead\x12\x16\n" +
	"\x06Height\x18\x03 \x01(\x04R\x06HeightB\x06Z\x04.;pbb\x06proto3"

var (
	file_bcast_proto_rawDescOnce sync.Once
	file_bcast_proto_rawDescData []byte
)

func file_bcast_proto_rawDescGZIP() []byte {
	file_bcast_proto_rawDescOnce.Do(func() {
		file_bcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bcast_proto_rawDesc), len(file_bcast_proto_rawDesc)))
	})
	return file_bcast_proto_rawDescData
}

var file_bcast_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bcast_proto_goTypes = []any{
	(*StateBroadcast)(nil), // 0: crdt.pb.StateBroadcast
	(*Participant)(nil),    // 1: crdt.pb.Participant
	(*Head)(nil),           // 2: crdt.pb.Head
	(*Snapshot)(nil),       // 3: crdt.pb.Snapshot
	nil,                    // 4: crdt.pb.StateBroadcast.MembersEntry
	nil,                    // 5: crdt.pb.Participant.MetadataEntry
}
var file_bcast_proto_depIdxs = []int32{
	4, // 0: crdt.pb.StateBroadcast.Members:type_name -> crdt.pb.StateBroadcast.MembersEntry
	2, // 1: crdt.pb.Participant.DagHeads:type_name -> crdt.pb.Head
	5, // 2: crdt.pb.Participant.metadata:type_name -> crdt.pb.Participant.MetadataEntry
	3, // 3: crdt.pb.Participant.Snapshot:type_name -> crdt.pb.Snapshot
	2, // 4: crdt.pb.Snapshot.SnapshotKey:type_name -> crdt.pb.Head
	2, // 5: crdt.pb.Snapshot.DagHead:type_name -> crdt.pb.Head
	1, // 6: crdt.pb.StateBroadcast.MembersEntry.value:type_name -> crdt.pb.Participant
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_bcast_proto_init() }
func file_bcast_proto_init() {
	if File_bcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bcast_proto_rawDesc), len(file_bcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bcast_proto_goTypes,
		DependencyIndexes: file_bcast_proto_depIdxs,
		MessageInfos:      file_bcast_proto_msgTypes,
	}.Build()
	File_bcast_proto = out.File
	file_bcast_proto_goTypes = nil
	file_bcast_proto_depIdxs = nil
}
