// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delta.proto

package crdt_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Delta struct {
	Elements             []*Element `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	Tombstones           []*Element `protobuf:"bytes,2,rep,name=tombstones,proto3" json:"tombstones,omitempty"`
	Priority             uint64     `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Delta) Reset()         { *m = Delta{} }
func (m *Delta) String() string { return proto.CompactTextString(m) }
func (*Delta) ProtoMessage()    {}
func (*Delta) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f1fd9d66f078a0, []int{0}
}

func (m *Delta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Delta.Unmarshal(m, b)
}
func (m *Delta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Delta.Marshal(b, m, deterministic)
}
func (m *Delta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Delta.Merge(m, src)
}
func (m *Delta) XXX_Size() int {
	return xxx_messageInfo_Delta.Size(m)
}
func (m *Delta) XXX_DiscardUnknown() {
	xxx_messageInfo_Delta.DiscardUnknown(m)
}

var xxx_messageInfo_Delta proto.InternalMessageInfo

func (m *Delta) GetElements() []*Element {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (m *Delta) GetTombstones() []*Element {
	if m != nil {
		return m.Tombstones
	}
	return nil
}

func (m *Delta) GetPriority() uint64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type Element struct {
	// key+id must form a unique identifier
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Element) Reset()         { *m = Element{} }
func (m *Element) String() string { return proto.CompactTextString(m) }
func (*Element) ProtoMessage()    {}
func (*Element) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f1fd9d66f078a0, []int{1}
}

func (m *Element) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Element.Unmarshal(m, b)
}
func (m *Element) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Element.Marshal(b, m, deterministic)
}
func (m *Element) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Element.Merge(m, src)
}
func (m *Element) XXX_Size() int {
	return xxx_messageInfo_Element.Size(m)
}
func (m *Element) XXX_DiscardUnknown() {
	xxx_messageInfo_Element.DiscardUnknown(m)
}

var xxx_messageInfo_Element proto.InternalMessageInfo

func (m *Element) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Element) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Element) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*Delta)(nil), "crdt.pb.Delta")
	proto.RegisterType((*Element)(nil), "crdt.pb.Element")
}

func init() { proto.RegisterFile("delta.proto", fileDescriptor_c9f1fd9d66f078a0) }

var fileDescriptor_c9f1fd9d66f078a0 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x49, 0xcd, 0x29,
	0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2e, 0x4a, 0x29, 0xd1, 0x2b, 0x48,
	0x52, 0x6a, 0x66, 0xe4, 0x62, 0x75, 0x01, 0x49, 0x08, 0xe9, 0x70, 0x71, 0xa4, 0xe6, 0xa4, 0xe6,
	0xa6, 0xe6, 0x95, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x09, 0xe8, 0x41, 0x55, 0xe9,
	0xb9, 0x42, 0x24, 0x82, 0xe0, 0x2a, 0x84, 0x0c, 0xb8, 0xb8, 0x4a, 0xf2, 0x73, 0x93, 0x8a, 0x4b,
	0xf2, 0xf3, 0x52, 0x8b, 0x25, 0x98, 0x70, 0xa8, 0x47, 0x52, 0x23, 0x24, 0xc5, 0xc5, 0x51, 0x50,
	0x94, 0x99, 0x5f, 0x94, 0x59, 0x52, 0x29, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe7, 0x2b,
	0x39, 0x72, 0xb1, 0x43, 0xb5, 0x08, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0x98, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x4c, 0x60, 0x01, 0xa6,
	0xcc, 0x14, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0xb0, 0x29, 0x3c, 0x41, 0x10,
	0x4e, 0x12, 0x1b, 0xd8, 0x63, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xde, 0xa3, 0x25, 0x9e,
	0xe7, 0x00, 0x00, 0x00,
}
