// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: delta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Element             `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	Tombstones    []*Element             `protobuf:"bytes,2,rep,name=tombstones,proto3" json:"tombstones,omitempty"`
	Priority      uint64                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_delta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_delta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_delta_proto_rawDescGZIP(), []int{0}
}

func (x *Delta) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *Delta) GetTombstones() []*Element {
	if x != nil {
		return x.Tombstones
	}
	return nil
}

func (x *Delta) GetPriority() uint64 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type Element struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key+id must form a unique identifier
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_delta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_delta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_delta_proto_rawDescGZIP(), []int{1}
}

func (x *Element) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Element) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Element) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_delta_proto protoreflect.FileDescriptor

const file_delta_proto_rawDesc = "" +
	"\n" +
	"\vdelta.proto\x12\acrdt.pb\"\x83\x01\n" +
	"\x05Delta\x12,\n" +
	"\belements\x18\x01 \x03(\v2\x10.crdt.pb.ElementR\belements\x120\n" +
	"\n" +
	"tombstones\x18\x02 \x03(\v2\x10.crdt.pb.ElementR\n" +
	"tombstones\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x04R\bpriority\"A\n" +
	"\aElement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05valueB\x06Z\x04.;pbb\x06proto3"

var (
	file_delta_proto_rawDescOnce sync.Once
	file_delta_proto_rawDescData []byte
)

func file_delta_proto_rawDescGZIP() []byte {
	file_delta_proto_rawDescOnce.Do(func() {
		file_delta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delta_proto_rawDesc), len(file_delta_proto_rawDesc)))
	})
	return file_delta_proto_rawDescData
}

var file_delta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delta_proto_goTypes = []any{
	(*Delta)(nil),   // 0: crdt.pb.Delta
	(*Element)(nil), // 1: crdt.pb.Element
}
var file_delta_proto_depIdxs = []int32{
	1, // 0: crdt.pb.Delta.elements:type_name -> crdt.pb.Element
	1, // 1: crdt.pb.Delta.tombstones:type_name -> crdt.pb.Element
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_delta_proto_init() }
func file_delta_proto_init() {
	if File_delta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delta_proto_rawDesc), len(file_delta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delta_proto_goTypes,
		DependencyIndexes: file_delta_proto_depIdxs,
		MessageInfos:      file_delta_proto_msgTypes,
	}.Build()
	File_delta_proto = out.File
	file_delta_proto_goTypes = nil
	file_delta_proto_depIdxs = nil
}
